CREATE TABLE IF NOT EXISTS meals_logs(
log_id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INTEGER NOT NULL,
meal_name TEXT NOT NULL,
calories INTEGER NOT NULL,
meal_type TEXT NOT NULL,
date TEXT NOT NULL,
time TEXT NOT NULL,
created_at TEXT NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(user_id)
);